/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEGame2048Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "fetchCipherScores"
      | "getRunCount"
      | "hasEncryptedData"
      | "protocolId"
      | "recordEncryptedRun"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "fetchCipherScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRunCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEncryptedData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordEncryptedRun",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "fetchCipherScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRunCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasEncryptedData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordEncryptedRun",
    data: BytesLike
  ): Result;
}

export interface FHEGame2048 extends BaseContract {
  connect(runner?: ContractRunner | null): FHEGame2048;
  waitForDeployment(): Promise<this>;

  interface: FHEGame2048Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fetchCipherScores: TypedContractMethod<
    [gamer: AddressLike],
    [string[]],
    "view"
  >;

  getRunCount: TypedContractMethod<[gamer: AddressLike], [bigint], "view">;

  hasEncryptedData: TypedContractMethod<
    [gamer: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recordEncryptedRun: TypedContractMethod<
    [cipherScore: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fetchCipherScores"
  ): TypedContractMethod<[gamer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRunCount"
  ): TypedContractMethod<[gamer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasEncryptedData"
  ): TypedContractMethod<[gamer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordEncryptedRun"
  ): TypedContractMethod<
    [cipherScore: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
